/**
 * Structured error with diagnostic context
 * Extends Error with machine-readable metadata
 */
class DiagnosticError extends Error {
  constructor(message, context = {}) {
    super(message);
    this.name = 'DiagnosticError';
    this.timestamp = new Date().toISOString();
    this.context = {
      errorType: context.errorType || 'UNKNOWN',
      severity: context.severity || 'ERROR', // ERROR, WARNING, CRITICAL
      component: context.component || 'unknown',
      rootCause: context.rootCause || null,
      recommendedFix: context.recommendedFix || null,
      relatedFiles: context.relatedFiles || [],
      environment: {
        node: process.version,
        platform: process.platform,
        cwd: process.cwd(),
        ...context.environment
      },
      metadata: context.metadata || {}
    };
  }

  toJSON() {
    return {
      name: this.name,
      message: this.message,
      stack: this.stack,
      timestamp: this.timestamp,
      context: this.context
    };
  }

  toGitHubIssue() {
    // Format for GitHub Issue creation
    return {
      title: `[AUTO-DIAGNOSTIC] ${this.context.errorType}: ${this.message}`,
      body: this.formatIssueBody(),
      labels: [this.context.severity.toLowerCase(), 'auto-diagnostic']
    };
  }

  formatIssueBody() {
    return `## 🚨 Auto-Diagnostic Report

**Error Type:** ${this.context.errorType}
**Severity:** ${this.context.severity}
**Component:** ${this.context.component}
**Timestamp:** ${this.timestamp}

### Error Message
\`\`\`
${this.message}
\`\`\`

### Root Cause Analysis
${this.context.rootCause || 'Pattern not recognized - manual investigation required'}

### Recommended Fix
${this.context.recommendedFix || 'See diagnostic snapshot below for context'}

### Environment
- Node: ${this.context.environment.node}
- Platform: ${this.context.environment.platform}
- Working Directory: ${this.context.environment.cwd}

### Related Files
${this.context.relatedFiles.map(f => `- ${f}`).join('\n') || 'None identified'}

### Stack Trace
\`\`\`
${this.stack}
\`\`\`

---
*Auto-generated by Diagnostic Infrastructure v1.0*
`;
  }
}

module.exports = { DiagnosticError };
